services:
  laravel-nginx:
    container_name: "laravel-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - laravel-app
    ports:
      - 80:88
    volumes:
      - ./:/src

  laravel-app:
    container_name: "laravel-app"
    build:
      context: ./docker/php
    depends_on:
      - laravel-mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      # - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  laravel-mysql:
    image: mysql:8.0.40
    command: --max_allowed_packet=32505856
    container_name: "laravel-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: db
        MYSQL_DATABASE: db
        TZ: Asia/Tokyo
    ports:
      - 3306:3306

  laravel-redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 16379:6379

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - laravel-mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: laravel-mysql
      PMA_USER: root 
      PMA_PASSWORD: db
    ports:
      - "3001:80"